# Generated by Django 4.1.5 on 2023-01-23 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RH_G4S', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Personne',
        ),
    ]
